import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Hero from '@/components/Hero'
import About from '@/components/About'
import Courses from '@/components/Courses'
import Testimonials from '@/components/Testimonials'
import Community from '@/components/Community'
import Enroll from '@/components/Enroll'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section id='#home'><Hero /></section>
        <section id='#about'><About /></section>
        <section id='#courses'><Courses /></section>
        <section id='#testimonials'><Testimonials /></section>
        <section id='#community'><Community /></section>
        <section><Enroll/></section>
        
        
        
        
        
        
        
        
      </main>
    </>
  )
}
